[package]
name = "todo"
version = "0.0.1"
authors = ["Mike Lubinets <lubinetsm@yandex.ru>"]

[dependencies]
time = "0.1"
docopt = "0.6"
rustc-serialize = "0.3"
ansi_term = "0.7"
log = "0.3.6"
env_logger = "0.3.3"
